-- 코드를 입력하세요
-- 년, 월, 성별 상품 굼한 회원 수

WITH BUYING_USER AS (
SELECT DISTINCT U.USER_ID, U.GENDER, YEAR(O.SALES_DATE) AS YEAR, MONTH(O.SALES_DATE) AS MONTH
FROM USER_INFO U JOIN ONLINE_SALE O
WHERE U.USER_ID = O.USER_ID AND U.GENDER IS NOT NULL
)

SELECT YEAR, MONTH, GENDER, COUNT(*) AS USERS
FROM BUYING_USER
GROUP BY YEAR, MONTH, GENDER
ORDER BY 1, 2, 3;