-- 코드를 입력하세요
WITH MAX_PRODUCT AS (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
)

SELECT F.CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT F JOIN MAX_PRODUCT M
ON F.CATEGORY = M.CATEGORY
WHERE F.PRICE = M.MAX_PRICE
ORDER BY 2 DESC;